Shirokov Ivan homework to hh-school-2023-java-collections-stream
ivan-bmstu/hh-school-2023-java-collections-stream pull request #1
Opened 2023-11-24 16:52 UTC by ivan-bmstu

Выполнил все 8 заданий.
Task 1 - асимптотика работы ~ const * O(n), подробнее в комментариях

Task2...7 выполнены, тесты проходят

Task8 - важно обсудить: 
1) переименовал два метода
getNames ==> getNamesExceptFirst
getDifferentNames ==> getDifferentNamesExceptFirst
Я не уверен что будет легко заменить наименование методов во всем проекте, по этому, прежде чем мержить в мастер, нужно обсудить это с командой (Олег, даешь добро на ренейминг? 😃 )
2) метод convertPersonToString на мой взгляд работает некорректно, он выдает "Фамилия Имя Фамилия", а по всей логике должен выдавать "Фамилия Имя Отчество". Это корректная логика метода, или нужно исправить?

p.s. написал методом тыка UnitTest к Task8 (оформление лучше не оценивать 😄) . Тест пришлось тоже менять, потому что convertPersonToString выдавал лишние пробелы
p.p.s. история коммитов оставляет желать лучшего, намудрил я с ветками.

2023-11-27 18:13 UTC, genroelgvozo requested changes

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +    return orderedPersons;
жесть как сложно)

работает конечно быстро, но только от одного getNullArrayList бросает в дрожь)

Подкину идею - тебе надо просто каждую айдишку превратить в свою персону (и это естественно выглядит красиво через стрим+мап), просто надо как-то быстро находить эту персону, а сет не подходит для этого...

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +                    .map(id -> person.getFirstName()
все гуд, единственное на будущее с точки зрения дальнейших правок кода - прикольно такой "формат" выносить в метод/конвертер, ведь это по факту какой-то фронт/апи формат. И тогда кажется метод сам захочет решать какие ему поля нужны из кандидата и арейки (ведь может не только быть название арейки, а какой-нибудь госномер). И тогда - удобно делать мапу айдишка на саму арейку а не ее имя (получается более универсально, код эффективно вызывающий конвертер не завязан на формат строки)

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * от пользователей, чтобы не были ясны некоторые "нужные" рабочие моменты. Это изменение обсуждаемо
про команду - ну ты берешь и ренейминг делаешь в проекте, оно само там везде)

а вот про скрытость - это в точку. Интерфейс не должен говорить реализацию (тут конечно вырожденный случай, обычно ты сразу получаешь персоны без всяких костылей, но я как пример), он должен говорить что возвращает, а не тонкости)

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * -заменил persons.size() == 0 на persons.isEmpty(), что будет эффективнее, если persons LinkedList
ну и обычно комментарий находится перед методом - хотя обычно комментов нет естественно

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * -заменил persons.size() == 0 на persons.isEmpty(), что будет эффективнее, если persons LinkedList
а зачем проверка на пустоту тебе?

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * но тут будет повторение кода (проверка на пустоту)
а тебе не захотелось сделать как я показывал на слайдах, когда говорил как НЕ НАДО юзать стримы?)

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * new HashSet<>(getNamesExceptFirst(persons))
аа, дочитал. а ты видимо лекцию не дослушал)

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * -выводится не ФИО, а ФИФ - тут непонятно, так и должно быть, или нужно править, поэтому обсуждаем с командой. Сейчас
ну конечно это баг, хотел показать что легко в исходном коде ошибиться - слишком много шелухи
а так абсолютно прав - такой код действительно легче менять

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * -воспользовался функционалом Collections
а какая асимптотика? и можно ли быстрее?

2023-11-27 18:13 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * убрал поле count, оно здесь избыточно
а чем еще плохо кроме избыточности? и вообще чем плох метод (даже получившийся, хоть и наилучшая версия)

2023-11-27 18:13 UTC, genroelgvozo commented on src/test/java/tasks/Task8Test.java
> +        assertFalse(task.hasSamePersons(persons1, persons4));
не знаю показывал в юнит тестах ли, но для такого используют ДатаПровайдер - общий метод теста, разные входные (и ожидаемые данные)

2023-11-27 18:32 UTC, ivan-bmstu commented on src/main/java/tasks/Task8.java
> +  * new HashSet<>(getNamesExceptFirst(persons))
Я дослушал, но что-то забыл что мы это обсуждали и полез в эти Гуглы, а там толкового ничего не нашел 😅

2023-11-27 19:45 UTC, ivan-bmstu commented on src/main/java/tasks/Task1.java
> +    return orderedPersons;
да уж, рил жуть(по сравнению с норм решением) я там натворил, не проникся к первой задаче философией стримов))

2023-11-27 21:12 UTC, ivan-bmstu commented on src/main/java/tasks/Task6.java
> +                    .map(id -> person.getFirstName()
Сделал словарь id - area, чтобы в стриме происходило нужное форматирование. 

Создал еще класс Task6Alternative, там такой же метод принимает еще BiFunction, чтобы на лету можно было менять форматирование person и area. Такой подход норм?

2023-11-27 21:29 UTC, ivan-bmstu commented on src/main/java/tasks/Task8.java
> +  * -заменил persons.size() == 0 на persons.isEmpty(), что будет эффективнее, если persons LinkedList
Проверка была изначалаьна, только через size()==0. Я думал, что если мы будем вызывать skip в stream от пустой коллекции, то получим какое-нибдь исключение. Проверил в jShell, ничего подобного, так что да, не нужна проверка

2023-11-27 21:29 UTC, ivan-bmstu commented on src/main/java/tasks/Task8.java
> +  * но тут будет повторение кода (проверка на пустоту)
упс))

2023-11-27 22:04 UTC, ivan-bmstu commented on src/main/java/tasks/Task8.java
> +  * -воспользовался функционалом Collections
Сейчас асимптотика O(n*m) в худшим случае. Можно быстрее, если сначала Collection привести к HashSet, тогда const*O(x), где х -  размер меньшей коллекции.

p.s. не хочется добавлять проверку изначально instanceof на HashSet, если оставлю как сейчас - будем проигрывать по памяти, зато код читаемый.

2023-11-27 22:13 UTC, ivan-bmstu commented on src/main/java/tasks/Task8.java
> +  * убрал поле count, оно здесь избыточно
Ну я бы передавал List<Integer>, а то вдруг поток прервется, а мы это никак не обрабатываем, потому что и не знаем, откуда Stream идет. Странная сигнатура метода

2023-11-27 22:13 UTC, ivan-bmstu commented on src/test/java/tasks/Task8Test.java
> +        assertFalse(task.hasSamePersons(persons1, persons4));
Да, там показывали и такое, но я пока не особо разобрался, решил на быструю руку сделать тяп ляп

2023-11-27 22:20 UTC, ivan-bmstu commented on src/main/java/tasks/Task8.java
> +  * от пользователей, чтобы не были ясны некоторые "нужные" рабочие моменты. Это изменение обсуждаемо
Я просто подумал, что могут же быть и удаленные вызовы функций, нам это показывали на вводной лекции по школе, где front просто ссылается на функцию бэка или что-то такое, мог напутать

2023-11-30 13:09 UTC, ivan-bmstu commented on src/test/java/tasks/Task8Test.java
> +        assertFalse(task.hasSamePersons(persons1, persons4));
Привел к лучшему виду unit test на task8, но там явно не все случаи покрыл (null, различная комбинаторика и тд)

2023-11-30 16:56 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  * -воспользовался функционалом Collections
ну вообще O(n+m), так как превращение в хешсет тоже стоит денег) но уже не произведение

2023-11-30 16:57 UTC, genroelgvozo approved these changes

2023-11-30 16:57 UTC, genroelgvozo commented on src/main/java/tasks/Task6Alternative.java
> +                                                    BiFunction<Person, Area, String> personDescription) {
такое вполне да, но обычно этот код сам знает что за конвертер вызвать) т.е. эта функция может просто рядом быть определена. Но бывает нужно конечно дженерности, тогда так делать норм

2023-12-14 11:45 UTC, merged